const pages=[...document.querySelectorAll('[data-page]')];
const counter=document.querySelector('#counter');
const goNext=()=>{const next=pages.find(page=>page.getBoundingClientRect().top>10);(next||pages[0]).scrollIntoView({behavior:'smooth'})};
document.querySelector('#nextTop').addEventListener('click',goNext);
document.querySelectorAll('.next').forEach(button=>button.addEventListener('click',goNext));
document.querySelector('#restart').addEventListener('click',()=>pages[0].scrollIntoView({behavior:'smooth'}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)counter.textContent=`${String(pages.indexOf(entry.target)+1).padStart(2,'0')} / 15`;}),{threshold:.65});pages.forEach(page=>observer.observe(page));
document.querySelectorAll('video[data-stop]').forEach(video=>video.addEventListener('timeupdate',()=>{if(video.currentTime>=Number(video.dataset.stop)){video.pause();video.currentTime=0;}}));
const resets=['A capybara has approved your vibe today. It is official.','You have been awarded one imaginary warm croissant.','A tiny frog is cheering for you from a leaf somewhere. Probably.','Your bad mood has been placed in a box marked “return to sender.”','Today’s forecast: 99% chance you deserve a snack and a nap.'];
document.querySelector('#laugh').addEventListener('click',()=>{document.querySelector('#result').textContent=resets[Math.floor(Math.random()*resets.length)];});
function sound(type){const ctx=new(window.AudioContext||window.webkitAudioContext)(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);if(type==='horn'){osc.type='sawtooth';osc.frequency.setValueAtTime(180,ctx.currentTime);osc.frequency.setValueAtTime(230,ctx.currentTime+.2);gain.gain.setValueAtTime(.22,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.8);osc.start();osc.stop(ctx.currentTime+.8);return;}if(type==='meow'){osc.type='triangle';osc.frequency.setValueAtTime(720,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(430,ctx.currentTime+.35);gain.gain.setValueAtTime(.16,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.45);osc.start();osc.stop(ctx.currentTime+.45);return;}const notes=type==='boing'?[170,440]:[560,780];notes.forEach((note,index)=>setTimeout(()=>{osc.frequency.setValueAtTime(note,ctx.currentTime);gain.gain.setValueAtTime(.12,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.18)},index*100));osc.start();osc.stop(ctx.currentTime+.45)}
document.querySelectorAll('[data-sound]').forEach(button=>button.addEventListener('click',()=>sound(button.dataset.sound)));
const forgive=document.querySelector('#forgive'),forgiveNote=document.querySelector('#forgiveNote');const dodgeNotes=['Nice try, Aru. The button has fled to Bangalore.','Arre arre, catch it first.','Forgiveness application is buffering…','Button says: “one more try, madam.”','Plot twist: it is faster than Rishit after the Tommy joke.'];let dodges=0;forgive?.addEventListener('pointerenter',()=>{if(dodges<5){forgive.style.transform=`translate(${(Math.random()-.5)*250}px, ${(Math.random()-.5)*120}px)`;forgiveNote.textContent=dodgeNotes[dodges++];}else{forgive.style.transform='translate(0,0)';forgive.textContent='forgiven? 🥹';forgiveNote.textContent='Okay okay, it has stopped running. Your call, Aru.';}});
